# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 08:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('num_of_lessons', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=20000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course')),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('isOnline', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(related_name='_newuser_friends_+', to='login.NewUser')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('progress_until_now', models.CharField(max_length=20000)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Lesson')),
                ('newuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.NewUser')),
            ],
        ),
    ]
