# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.CharField(default=None, max_length=20000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
