# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='expected_output',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
