# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('progress_until_now', models.CharField(max_length=20000)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Challenge')),
                ('newuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.NewUser')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islessonornot', models.BooleanField(default=False)),
                ('whichone', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course')),
                ('newuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.NewUser')),
            ],
        ),
    ]
