# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_challengeprogress_courselocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselocation',
            name='whichone',
            field=models.CharField(max_length=200),
        ),
    ]
