# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20161121_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeprogress',
            name='progress_until_now',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress_until_now',
            field=models.TextField(default=''),
        ),
    ]
