# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20161121_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lesson',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='expected_output',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='expected_output',
            field=models.CharField(default='', max_length=200),
        ),
    ]
